# Exported from Render on 2025-08-06T01:09:10Z
databases:
- name: cookbook-db
  databaseName: cookbook_db_t2bn
  user: cookbook_db_t2bn_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "17"
version: "1"
